config/routes.rb
Rails.application.routes.draw do
  get 'calendar/show'

  devise_for :users
  
  resources :users, only: [:index, :show]
  
  root 'static_pages#home2'
  
  get '/administrador' => 'static_pages#admin'
  get '/contactenos' => 'static_pages#contactenos'
  get '/about' => 'static_pages#about'
  
  get '/contacts',     to: 'contacts#new'
  resources "contacts", only: [:new, :create]
  
  resources :events
  
  resource :calendar, only: [:show], controller: :calendar
  
  get '/calendar' => 'calendar#show'
  
  

  
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :subject,   :validates => true
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => %("#{subject}"), #"Formulario de Contacto",
      :to => "javaEE2015@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
    
    belongs_to :user
    
    validates :title, presence: true, length: { minimum: 3 }
    validates :body, presence: true, length: { minimum: 30 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
         
  def full_name
    if self.name.blank?
      self.email
    else
      self.name
    end
  end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :configure_permitted_parameters, if: :devise_controller?

    def after_sign_in_path_for(resource)
      if current_user.role == 0
        "/administrador"
      else if current_user.role == 1
          "/contactenos"
        end
      end
    end
    
    def authorize_admin
      if !current_user
        redirect_to root_path, alert: 'Access Denied, necesita loguerse antes'
        return
      end
      if current_user.role != 0
        redirect_to root_path, alert: 'Access Denied' #unless current_user.admin?
        return
      end
    end
  
    protected
      def configure_permitted_parameters
          devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
          devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :last_name, :email, :password, :current_password, :is_female, :date_of_birth) }
      end
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  def show
        @date = params[:date] ? Date.parse(params[:date]) : Date.today
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Gracias por el mensaje. Nos comunicaremos a la brevedad'
    else
      flash.now[:error] = 'No se pudo enviar el mensaje.'
      render :new
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    
    before_filter :authorize_admin, only: [:new,:create]
    #before_filter :authenticate_user! #, except: [:show, :index] #en este caso solo usuarios logueados pueden ver noticias
    
    def index
        @events = Event.all
    end

    def show
        @event = Event.find(params[:id])
    end

    def new
        @event = Event.new
    end
    
    def create
        @user = current_user
        @event = Event.new(allowed_params)

        if @event.save
            flash[:success] = "Created new event"
            redirect_to @event
        else
            render 'new'
        end
    end

    private
        def allowed_params
            params.require(:event).permit(:title, :body)
        end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def home
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end
    
    def show
        @user = User.find(params[:id])
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def resource_name
      :user
    end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/calendar/show.html.erb
<h1>Calendar#show</h1>
<p>Find me in app/views/calendar/show.html.erb</p>

<div class="row">
  <div class="col-md-12 text-center">
    <div class="well controls">
      <%= link_to calendar_path(date: @date - 1.month), class: "btn btn-default" do %>
        <i class="glyphicon glyphicon-backward"></i>
      <% end %>
      <%= "#{@date.strftime("%B")} #{@date.year}" %>
      <%= link_to calendar_path(date: @date + 1.month), class: "btn btn-default" do %>
        <i class="glyphicon glyphicon-forward"></i>
      <% end %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <%= calendar @date do |date| %>
      <%= date.day %>  
    <% end %>
  </div>
</div>

app/views/contacts/create.html.erb
<!--<div>-->
<!--  <%# flash.each do |key, value| %>-->
<!--    <div>-->
<!--      <a href="#" data-dismiss="alert">×</a>-->
<!--        <%#= value %>-->
<!--    </div>-->
<!--  <%# end %>-->
<!--</div>-->

app/views/contacts/new.html.erb
<!--<div align="center">-->
<!--  <h3>Send A message to Us </h3>-->

<!--  <%#= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>-->
<!--    <%#= f.input :name, :required => true %>-->
<!--    <%#= f.input :email, :required => true %>-->
<!--    <%#= f.input :message, :as => :text, :required => true %>-->
<!--    <div class= "hidden">-->
<!--      <%#= f.input :nickname, :hint => 'Leave this field blank!' %>-->
<!--    </div>-->
<!--    <div>-->
<!--      </br>-->
<!--      <%#= f.button :submit, 'Send message', :class=> "btn btn-primary" %>-->
<!--    </div>-->
<!--  <%# end %>-->
<!--</div>-->
        <div class="container" style="margin-top:50px;">
            <%= form_for @contact  do |f| %>
                <div class="row">
                    <div class="col-lg-12 text-center">
                        <h2 class="section-heading">Cont&aacute;ctenos</h2>
                        <h3 class="section-subheading text-muted">P&oacute;ngase en contacto con el tecn&oacute;logo.</h3>
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-lg-6">
                        
                        <div class="form-group">
                            <%= f.text_field :name, type:'text', class:'form-control', placeholder:'Ingrese su nombre *'%>
                            <p class="help-block text-danger"></p>
                        </div>
                        
                        <div class="form-group">
                            <%= f.text_field :email, :required => true, type:'text', class:'form-control', placeholder:'Ingrese su e-mail *'%>
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="form-group">
                            <%= f.text_field :subject, :required => true, type:'text', class:'form-control', placeholder:'Ingrese su e-mail *'%>
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            
                            <%= f.text_area :message, :as => :text, :required => true, type:'text', class:'form-control', placeholder:'Ingrese su Mensaje *'%>
                            <p class="help-block text-danger"></p>
                            
                            <div class="col-lg-12 text-center btnmap">
                                <h5 class="section-subheading text-muted">Coordinadora: <font color="Black">Ana Iruleguy</font></h5>
                                <div  style="margin-top: 5px;">
                                    <i class="glyphicon glyphicon-envelope">
                                    </i> tipay.2009@gmail.com
                                </div>
                                <div  style="margin-top: 5px;">
                                    <i class="glyphicon glyphicon-home">
                                        
                                    </i> Leandro G&oacute;mez y 33 Orientales S/N.
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <div class="col-lg-12 text-center">
                        <div id="success"></div>
                        <%= f.submit 'Send message', :class=> "btn btn-default btn-lg" %>
                    </div>
                </div>
            <% end %>
        </div>

app/views/events/index.html.erb
<h1>This will be a list of events</h1>
<%= link_to 'New Post', new_event_path %>
<ul>
        <% @events.each do |p| %>
            <li>
                <h3><%= link_to p.title, event_path(p.id) %></h3>
                <p><%= p.body %></p>
            </li>
        <% end %>
    </ul>

app/views/events/new.html.erb
    <%= form_for @event do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
        <div class="form-group">
            <%= f.label :title, class: 'control-label' %>
            <%= f.text_field :title, class: 'form-control' %>
        </div>

        <div class="form-group">
            <%= f.label :body, class: 'control-label' %>
            <%= f.text_area :body, class: 'form-control', rows: 6 %>
        </div>

        <%= f.submit 'Save', class: 'btn btn-primary' %>
    <% end %>

app/views/events/show.html.erb
    <h1>This will be a individual event page</h1>
    
    
    <h1><%= @event.title %></h1>
    <p><%= @event.body %></p>
    <p><%= @event.fecha %></p>

app/views/layouts/_cabezal.html.erb
<!-- COMIENZO DE HEADER -->
<nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
    <div class="container topnav">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to "TecnoInf ", root_path, class:'navbar-brand topnav'%>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                
                <% if current_user %>    
                    <% if current_user.role==0 %>
                        <li>    
                            <a href="#about">Bienvenido Admin</a>
                        </li>
                        <li>
                            <%= link_to 'Members', users_path %>
                        </li>
                    <% else  %>
                        <li>    
                            <a href="#about">Bienvenido Alumno</a>
                        </li>
                    <%end%>
                    
                <%end %>
                
                <li>
                    <a href="#about">Nosotros</a>
                </li>
                <li>
                    <a href="#services">Servicios</a>
                </li>
                <li>
                    <a href="#contact">Contact</a>
                </li>
                <!--
                  <li>
                    <form class="navbar-form navbar-right">
                      <a href="#myModalOut" class="btn btn-danger fa fa-sign-out" data-toggle="modal"> Log Out</a>
                    </form>
                  </li>
                  -->
                        <li>
                            <form class="navbar-form navbar-right">
                                <%= link_to 'All Noticias', events_path,  class:'btn'  %>
                            </form>
                        </li>
                        <% if current_user %>
                        <li>
                            <form class="navbar-form navbar-right">
                               <li><%= link_to 'Editar Perfil' ,edit_user_registration_path, class:'btn' %></li>
                            </form
                        </li>
                            <li>
                                <form class="navbar-form navbar-right">
                                    <%= link_to 'Logout', destroy_user_session_path, method: :delete,  class:'fa fa-sign-out' %>
                                </form>
                            </li>
                        <% else %>
                            <li>
                                <a href="#myModalIn" class="btn fa fa-sign-in" data-toggle="modal"> Entrar</a>
                                <!--%= link_to 'Login', new_user_session_path %-->
                            </li>
                            <li>
                                <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
                                    <a href="#myModalSignUp" class="btn fa fa-sign-in" data-toggle="modal"> Registrar</a>
                                <% end -%>
                            </li>
                        <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav> <!--Fin de HEADER-->


   
    <!-- Modal HTML -->
    <form class="navbar-form navbar-right">
      <div id="myModalOut" class="modal fade">

          <div class="modal-dialog">

              <div class="modal-content">

                  <div class="modal-header">

                      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>

                      <h4 class="modal-title">Confirmacion</h4>

                  </div>

                  <div class="modal-body">

                      <p>Está seguro que desea Cerrar sesión?</p>

                  </div>

                  <div class="modal-footer">

                      <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>

                      <input type="submit" value="Log out" id="logoutUP" name="logoutUP" class="form-control btn btn-danger">

                  </div>

              </div>

          </div>

      </div>
    </form>
    
    <!--Modal de Log In-->
    <div id="myModalIn" class="modal fade">
    
      <div class="modal-dialog">
    
          <div class="modal-content">
    
              <div class="modal-header">
    
                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    
                  <h4 class="modal-title">Log In</h4>
    
              </div>
                <%= form_for(resource, as: resource_name, url: session_path(resource_name), html: {class: 'form-horizontal'}) do |f| %>
              <div class="modal-body">
                  
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-8 col-md-offset-2">
                                <%= f.label :email, class: "col-sm-2 control-label" %>
                                
                                    <%= f.email_field :email, autofocus: true , required:"", placeholder:'email@email.xxx', type:'text' ,class: "form-control" %>
                                
                            </div>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-8 col-md-offset-2">
                                <%= f.label :password, class: "col-sm-2 control-label" %>
                                
                                    <%= f.password_field :password, autocomplete: "off", required:"", placeholder:'Password' ,class: "form-control" %>
                                
                            </div>
                        </div>
                    </div>
                    
                    <% if devise_mapping.rememberable? -%>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-8 col-md-offset-2">
                                    <%= f.check_box :remember_me %>
                                    <%= f.label :remember_me %>
                                </div>
                            </div>
                        </div>
                      <% end -%>
               
                    </div>
    
              <div class="modal-footer">
    
                  <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
    
                  <%= f.submit "Log in", class: 'btn btn-danger' %>
    
              </div>
            <% end %>
          </div>
    
      </div>
    
    </div>
    
    <!-- Modal de registro -->
    <div id="myModalSignUp" class="modal fade">

          <div class="modal-dialog">

              <div class="modal-content">

                  <div class="modal-header">

                      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>

                      <h4 class="modal-title">Registro de Usuario</h4>

                  </div>
                <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: {class: 'form-horizontal'}) do |f| %>
                  
                
                    <!--el cuerpo del modal-->
                    
                    <div class="modal-body">

                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-8 col-md-offset-2">
                                <%= f.label :Nombre, class: "col-md-2 control-label" %>
                                <%= f.text_field :name, class: "form-control",autofocus: true %>
                            </div>
                        </div>
                    </div>
                      
                      
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-8 col-md-offset-2">
                                <%= f.label :Apellido %>
                                <%= f.text_field :last_name, class: "form-control",autofocus: true %>
                            </div>
                        </div>
                    </div>
                      
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-8 col-md-offset-2">
                            <div><%= f.check_box :is_male, {}, true %> <%= f.label :is_male, "Masculino" %> </div>
                            <div><%= f.check_box :is_male, {}, false %> <%= f.label :is_male, "Femenino" %> </div>
                            </div>
                        </div>
                    </div>
                      
                        
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-8 col-md-offset-2">
                                <%= f.label :Fecha_de_Nacimiento  %>
                                
                                    <%= f.date_select :date_of_birth, class: "form-control",autofocus: true %>
                                
                            </div>
                        </div>
                    </div>
                      
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-8 col-md-offset-2">
                                <%= f.label :Email %>
                                <%= f.email_field :email, class: "form-control", required:"", autofocus: true %>
                            </div>
                        </div>
                    </div>

                      <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
                        <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
                      <% end %>
                    
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-8 col-md-offset-2"> 
                                <%= f.label :Password %>
                                <%= f.password_field :password, autocomplete: "off", class: "form-control" %>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-8 col-md-offset-2"> 
                            <%= f.label :Confirmacion_Password %>
                            <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control" %>
                            </div>
                        </div>
                    </div>

                  </div>

                    <div class="modal-footer">
    
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                            
                        <%= f.submit "Registrar", class: "btn btn-primary" %>
                        
                         <!--input type="submit" value="Log out" id="logoutUP" name="logoutUP" class="form-control btn btn-danger"-->
                    </div>
                  <% end %>

              </div>

          </div>

      </div>

app/views/layouts/_flash_messages.html.erb
<!--alerta de mensajes-->

<% flash.each do |key, value| %>
    
    <div class="alert alert-<%= key %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <%= value %>
    </div>
<% end %>

<script>
    $('.alert').fadeOut(6000);
</script>

app/views/layouts/_footer.html.erb
<!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li>
                            <%= link_to "Home", root_path %>
                            
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#about">Nosotros</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#services">Servicios</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#contact">Contacto</a>
                        </li>
                    </ul>
                    <p class="copyright text-muted small">Copyright &copy; Tecnólogo en Informática Paysandú 2015. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                
            </button>
            <%= link_to "Para Java EE ", root_path, class: 'navbar-brand' %>
        </div>

        <div class="collapse navbar-collapse" id="navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                
                <li><%= link_to 'Members', users_path %></li>
                <% if current_user %>
                    <li><%= link_to 'Edit Profile',edit_user_registration_path %></li>
                    <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
                <% else %>
                    <li><%= link_to 'Login', new_user_session_path %></li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Java EE Usuarios</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    
    <style>
          body { padding-top: 50px; }
        </style>
    <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/cabezal' %>
<%= render 'layouts/flash_messages'%>
<%= yield %>

<%= render 'layouts/footer' %>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <p><strong>This form contains <%= pluralize(object.errors.count, 'errors') %>.</strong></p>
            <ul>
                <% object.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "Acerca del Tecnologo") %>

    
    <!--Encabezado-->
    
    <div class="head">
            <h3>ACERCA DEL TECNÓLOGO EN INFORMÁTICA</h3>
            </br>
    </div>   
    
    
    
    <body background="../Keyboard.jpg">
    
    
        <div class="container">
        
        </br>
        </br>
        </br>
        
         <div class="col-lg-offset-1">
            <div class="col-lg-11">
                
              <div class="opaca">
              <p><b>Duración: </b>3 años / 6 semestres</p> 
              </div>
              
              </br>
              
              <div class="opaca">
              <p><b>Requisitos de ingreso: </b>Pueden ingresar a la carrera tanto egresados del “Bachillerato Tecnológico de Procesamiento 
                  y Mantenimiento Informático”, de la “Enseñanza Media Tecnológica en Informática” y de los “Bachilleratos de Educación 
                  Secundaria” que habiliten el ingreso a la Facultad de Ingeniería.</p>
             </div>
             
             </br>
             
              <div class="opaca">
              <p><b>Perfil de egreso: </b>El Tecnólogo en Informática será capaz de desarrollar sistemas de pequeño y mediano porte y podrá integrarse a grupos de desarrollo de proyectos de porte superior. 
                  Contará con la habilidad de construir y evaluar soluciones informáticas abarcando las tareas de construcción, pruebas y documentación, integrando eventualmente distintas tecnologías.
                  La carrera de se dicta en forma conjunta entre la Universidad de la República (UdelaR) y la Administración Nacional de la Educación Pública (ANEP). En Paysandú los cursos se desarrollan en las instalaciones del Puerto Digital Regional (Paysandú Innova).</p>
              </div>
              
         </br>
         
             <p><a class="btn btn-primary" href="http://tareajava-cheloo.c9.io/" role="button">VOLVER</a></p>
        
            </div> 
         
         
         </div>  
         
         

    </div>
    
    </br>
    
    
    
    <!--Pie de pagina   LA CLASE FOOTER ESTA EN EL CSS DEFINIDA--> 
    <div class="footer">
            <p>2015, Paysandú, Uruguay</p>
            <p>Leandro Gómez y 33 Orientales S/N.</p>
            <p> tipay.2009@gmail.com</p>
    </div>
    

app/views/users/index.html.erb
<div class="container">
    <div class="users row">
        <% @users.each do |user| %>
        <div class="panel panel-default">
            <%= link_to user_path(user) do %>
            <div class="panel-body">
                <%= image_tag(user.avatar.url(:medium)) %>
                <p><%= user.full_name %></p>
            </div>
            <% end %>
        </div>
        <% end %>
    </div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<div class="row profile">
    <div class="col-sm-4 col-md-3">
        
        <h1><%= @user.full_name %></h1>
        <ul>
            <%= content_tag(:li, ("Name: " + @user.name)) unless @user.name.blank? %>
            <%= content_tag(:li, ("Age: " + distance_of_time_in_words(Time.now, @user.date_of_birth) + " old")) unless @user.date_of_birth.blank? %>
        </ul>
    </div>
    
</div>



<!-- lo que hace el segundo content_teg es resar la fecha actual con la de nacimiento y nos la edad, magia chavall -->